# Generated by Django 3.2.7 on 2021-09-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField(blank=True)),
                ('coordinate_lng', models.DecimalField(decimal_places=17, max_digits=20, verbose_name='долгота')),
                ('coordinate_lat', models.DecimalField(decimal_places=17, max_digits=20, verbose_name='широта')),
            ],
        ),
    ]
