# Generated by Django 3.2.7 on 2021-09-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210921_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='порядковый номер'),
        ),
    ]
